CUDA_VISIBLE_DEVICES=1, python3 train_iq.py \
--hidden_dim 1024 \
--latent_dim 1024 \
--pwffn_dim 2048 \
--enc_num_layers 16 \
--dec_num_layers 2 \
--num_heads 8 \
--batch_size 128 \
--num_pretraining_steps 10000 \
--enable_t_space False \
--use_gpu True \
--input_mode "ans" \
--print_note "Z path."
