CUDA_VISIBLE_DEVICES=1, python3 train_iq.py \
--hidden_dim 512 \
--latent_dim 512 \
--pwffn_dim 2048 \
--num_layers 6 \
--num_heads 8 \
--batch_size 64 \
--dropout 0.2 \
--num_pretraining_steps 6000 \
--total_training_steps 15000 \
--early_stop True \
--variant "transformer-latent-oca-lt" \
--print_note "Transformer decoder. Image features, object features, cat, ans (train only). Learned prior/post."
